#include "../common/sampapi.h"

#undef SAMPAPI_BEGIN
#define SAMPAPI_BEGIN SAMPAPI_NAMESPACE_BEGIN(v037r1)

#undef SAMPAPI_BEGIN_PACKED
#define SAMPAPI_BEGIN_PACKED SAMPAPI_NAMESPACE_BEGIN_PACKED(v037r1)
