/*
	This is a SAMP (0.3.7-R3) API project file.
	Developer: LUCHARE <luchare.dev@gmail.com>
	
	See more here https://github.com/LUCHARE/SAMP-API
	
	Copyright (c) 2018 BlastHack Team <BlastHack.Net>. All rights reserved.
*/

#pragma once

#include "sampapi/sampapi.h"

SAMPAPI_BEGIN_V037R3_1

enum SpecialAction {
    SPECIAL_ACTION_NONE,
    SPECIAL_ACTION_DUCK,
    SPECIAL_ACTION_USEJETPACK,
    SPECIAL_ACTION_ENTER_VEHICLE,
    SPECIAL_ACTION_EXIT_VEHICLE,
    SPECIAL_ACTION_DANCE1,
    SPECIAL_ACTION_DANCE2,
    SPECIAL_ACTION_DANCE3,
    SPECIAL_ACTION_DANCE4,
    SPECIAL_ACTION_HANDSUP,
    SPECIAL_ACTION_USECELLPHONE,
    SPECIAL_ACTION_SITTING,
    SPECIAL_ACTION_STOPUSECELLPHONE,
    SPECIAL_ACTION_DRINK_BEER = 20,
    SPECIAL_ACTION_SMOKE_CIGGY,
    SPECIAL_ACTION_DRINK_WINE,
    SPECIAL_ACTION_DRINK_SPRUNK,
    SPECIAL_ACTION_CUFFED,
    SPECIAL_ACTION_CARRY,
    SPECIAL_ACTION_URINATING = 68
};

SAMPAPI_END
